#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Set DPI. User may want to use a larger number for larger screens.
         # set the background with the `setbg` script

xrandr --dpi 112 # Set DPI. User may want to use a larger number for larger screens.
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xresources &
xrdbpid=$! # Uncomment to use Xresources colors/settings on startup

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

"$HOME/.local/share/dwm/autostart" > /dev/null 2>&1
